# Kay's DevOps Starship prompt

add_newline = true
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$docker_context\
$kubernetes\
$terraform\
$cmd_duration\
$line_break\
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold cyan)"

[username]
show_always = true
format = "[$user](bold cyan) "

[hostname]
ssh_only = false
format = "in [$hostname](bold green) "

[directory]
truncation_length = 3
truncate_to_repo = false
format = "in [$path](bold blue) "

[git_branch]
symbol = "🌱 "
format = "on [$symbol$branch](bold purple) "

[git_status]
format = "[$all_status$ahead_behind](bold yellow) "
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[python]
symbol = "🐍 "
format = "via [$symbol$version](bold yellow) "

[docker_context]
symbol = "🐳 "
format = "via [$symbol$context](bold blue) "

[kubernetes]
disabled = false
symbol = "☸ "
format = "on [$symbol$context](bold cyan) "

[terraform]
symbol = "💠 "
format = "via [$symbol$workspace](bold purple) "

[cmd_duration]
min_time = 2000
format = "took [$duration](bold yellow) "
